module SDL_HintPriority
( SDL_HintPriority(..)
, SDL_HINT_DEFAULT
, SDL_HINT_NORMAL
, SDL_HINT_OVERRIDE
) where

data SDL_HintPriority = SDL_HINT_DEFAULT | SDL_HINT_NORMAL | SDL_HINT_OVERRIDE

SDL_HINT_DEFAULT  = SDL_HINT_DEFAULT
SDL_HINT_NORMAL   = SDL_HINT_NORMAL
SDL_HINT_OVERRIDE = SDL_HINT_OVERRIDE
