module SDL_GLprofile
( SDL_GLprofile(..)
, SDL_GL_CONTEXT_PROFILE_CORE
, SDL_GL_CONTEXT_PROFILE_COMPATIBILITY
, SDL_GL_CONTEXT_PROFILE_ES
) where

type SDL_GLprofile = Int

SDL_GL_CONTEXT_PROFILE_CORE          = 0x0001
SDL_GL_CONTEXT_PROFILE_COMPATIBILITY = 0x0002
SDL_GL_CONTEXT_PROFILE_ES            = 0x0004
