module SDL_GLcontextFlag
( SDL_GLcontextFlag(..)
, SDL_GL_CONTEXT_DEBUG_FLAG
, SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG
, SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG
, SDL_GL_CONTEXT_RESET_ISOLATION_FLAG
) where

type SDL_GLcontextFlag = Int

SDL_GL_CONTEXT_DEBUG_FLAG = 0x001
SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG = 0x002
SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG = 0x004
SDL_GL_CONTEXT_RESET_ISOLATION_FLAG = 0x008
